CART Some OneLiner Scripts Added
ErdemOzgen/blackdagger-cart pull request #1
Opened 2024-03-25 20:47 UTC by RegaipKURT

I have been add some oneliner scripts to use with blackdagger.

2024-03-26 19:15 UTC, ErdemOzgen commented
@ataseren will tested all of them

2024-03-27 08:28 UTC, ataseren requested changes
I tested all YAMLs in Blackcart since it has a preconfigured environment for CART purposes. With few additions, all YAMLs run as expected. Required changes are:

- Escape sequence issue with the parameters used in scripts
- Installation of missing tools in Blackcart
- For some YAMLs, I added specific additions as comments. They must be modified as well.

One final comment, these YAMLs are designed to run in Blackcart because of the environment configs in YAMLs. By changing or commenting them, we can make these YAMLs suitable for all environments.

2024-03-27 08:28 UTC, ataseren commented on XSS.yaml
This YAML works fine. However, I used a method to remove the quotation marks from the parameter. I think it is solved in one of the versions of Blackdagger. If not, it is easy but important to fix.

2024-03-27 08:28 UTC, ataseren commented on OpenRedirect.yaml
This YAML works fine. However, I used a method to remove the quotation marks from the parameter. I think it is solved in one of the versions of Blackdagger. If not, it is easy but important to fix.

2024-03-27 08:28 UTC, ataseren commented on SSRF.yaml
"anew" command is not installed in my version of Blackcart. However, the command doesn't work in both Blackdagger and Blackcart terminal after installing "anew". I think the problem is at "gf" command.

2024-03-27 08:28 UTC, ataseren commented on LFI.yaml
This command doesn't work in both Blackdagger and Blackcart. I think the problem is at "gf" command.

2024-03-27 08:28 UTC, ataseren commented on CORS_Misconfig.yaml
I stopped the scan since it took so long but I think it works. However, I used a method to remove the quotation marks from the parameter. I think it is solved in one of the versions of Blackdagger. If not, it is easy but important to fix.

2024-03-27 08:28 UTC, ataseren commented on SubfinderNuclei.yaml
This YAML works fine. However, I used a method to remove the quotation marks from the parameter. I think it is solved in one of the versions of Blackdagger. If not, it is easy but important to fix.

2024-03-27 08:28 UTC, ataseren commented on LFI.yaml
Installed the missing commands.

2024-03-27 08:28 UTC, ataseren commented on LFI.yaml
There was an issue about xargs which it gives exit status 123. xargs exits with 123  if any invocation of the command exited with status 1-125 (https://www.commandlinux.com/man-page/man1/xargs.1.html)

I broke down the code and realized that curl gives exit status 1 when it can't reach to a URL or receives an error HTML code such as 4xx or 5xx. To overcome this issue, I added  " || true in the xargs command. In this way, none of the other commands will be affected from this but if curl gives an error, it will be supressed. At the end, the command runs correctly with the additions made.

2024-03-27 08:28 UTC, ataseren commented on SSRF.yaml
Installed the missing commands.

2024-03-27 08:28 UTC, ataseren commented on SSRF.yaml
There was an issue about xargs which it gives exit status 123. xargs exits with 123  if any invocation of the command exited with status 1-125 (https://www.commandlinux.com/man-page/man1/xargs.1.html)

I broke down the code and realized that curl gives exit status 1 when it can't reach to a URL or receives an error HTML code such as 4xx or 5xx. To overcome this issue, I added  " || true in the xargs command. In this way, none of the other commands will be affected from this but if curl gives an error, it will be supressed. At the end, the command runs correctly with the additions made.

2024-03-27 10:13 UTC, merged